# Generated by Django 5.2.5 on 2025-08-27 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('summary_description', models.CharField(default='Total de vendas do dia', help_text='Uma descrição padronizada do total de vendas diário.', max_length=255, verbose_name='Descrição do Lançamento')),
                ('date', models.DateField(help_text='Data em que a venda foi efetuada.', verbose_name='Data da Venda')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='O valor total da transação.', max_digits=10, verbose_name='Valor Total')),
                ('sale_type', models.CharField(choices=[('PRODUCT', 'Produto'), ('SERVICE', 'Serviço'), ('IN_STORE', 'Na Loja')], default='IN_STORE', max_length=10, verbose_name='Tipo de Venda')),
                ('description', models.TextField(blank=True, help_text='Observações adicionais sobre a venda.', null=True, verbose_name='Descrição')),
                ('seller', models.ForeignKey(help_text='Usuário que realizou a venda.', on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda Diária',
                'verbose_name_plural': 'Vendas Diárias',
            },
        ),
    ]
