# Generated by Django 5.2.5 on 2025-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='item_sold',
        ),
        migrations.AddField(
            model_name='dailysale',
            name='summary_description',
            field=models.CharField(default='Total de vendas do dia', help_text='Uma descrição padronizada do total de vendas diário.', max_length=255, verbose_name='Descrição do Lançamento'),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='sale_type',
            field=models.CharField(choices=[('PRODUCT', 'Produto'), ('SERVICE', 'Serviço'), ('IN_STORE', 'Na Loja')], default='IN_STORE', max_length=10, verbose_name='Tipo de Venda'),
        ),
    ]
