# Generated by Django 5.2.5 on 2025-08-23 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Regra')),
                ('rule_type', models.CharField(choices=[('FLAT', 'Valor Fixo'), ('TIERED', 'Por Faixa'), ('BONUS', 'Bônus')], help_text='Define como a comissão será calculada (fixa, por faixas, etc.).', max_length=10, verbose_name='Tipo de Regra')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou a regra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Regra de Comissão',
                'verbose_name_plural': 'Regras de Comissão',
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('limit_value', models.DecimalField(decimal_places=2, help_text='O valor máximo de vendas para aplicar este percentual.', max_digits=10, verbose_name='Valor Limite da Faixa')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='A comissão a ser paga nesta faixa.', max_digits=5, verbose_name='Percentual (%)')),
                ('rule', models.ForeignKey(help_text='A qual regra de comissão esta faixa pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.commissionrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Faixa de Comissão',
                'verbose_name_plural': 'Faixas de Comissão',
                'ordering': ['rule', 'limit_value'],
            },
        ),
        migrations.CreateModel(
            name='CommissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('period_year', models.PositiveIntegerField(verbose_name='Ano do Período')),
                ('period_month', models.PositiveIntegerField(verbose_name='Mês do Período')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vendas Totais no Período')),
                ('calculated_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comissão Calculada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('PAID', 'Pago')], default='PENDING', max_length=10, verbose_name='Status')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Data em que o relatório foi fechado e não pode mais ser alterado.', null=True, verbose_name='Fechado em')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reports', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('commission_rule_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commissionrule', verbose_name='Regra Aplicada')),
            ],
            options={
                'verbose_name': 'Relatório de Comissão',
                'verbose_name_plural': 'Relatórios de Comissão',
                'unique_together': {('seller', 'period_year', 'period_month')},
            },
        ),
    ]
