# Generated by Django 5.2.5 on 2025-08-27 00:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Regra')),
                ('rule_type', models.CharField(choices=[('FLAT', 'Valor Fixo'), ('TIERED', 'Por Faixa'), ('BONUS', 'Bônus')], help_text='Define como a comissão será calculada (fixa, por faixas, etc.).', max_length=10, verbose_name='Tipo de Regra')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('flat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Percentual aplicado para regras do tipo 'Valor Fixo'.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Percentual Fixo (%)')),
                ('bonus_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentual'), ('FIXED', 'Valor Fixo')], help_text='Define se o bônus é percentual ou valor fixo.', max_length=10, null=True, verbose_name='Tipo de Bônus')),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do bônus, que pode ser percentual ou fixo.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Bônus')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou a regra.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Regra de Comissão',
                'verbose_name_plural': 'Regras de Comissão',
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='O valor mínimo de vendas para aplicar este percentual.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Mínimo da Faixa')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='O valor máximo de vendas para aplicar este percentual. Deixe em branco para a última faixa.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Máximo da Faixa')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='A comissão a ser paga nesta faixa.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual (%)')),
                ('rule', models.ForeignKey(help_text='A qual regra de comissão esta faixa pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.commissionrule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Faixa de Comissão',
                'verbose_name_plural': 'Faixas de Comissão',
                'ordering': ['rule', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='CommissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar o registro em vez de excluí-lo.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('period_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano do Período')),
                ('period_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês do Período')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vendas Totais no Período')),
                ('calculated_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comissão Calculada')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('PAID', 'Pago')], default='PENDING', max_length=10, verbose_name='Status')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Data em que o relatório foi fechado e não pode mais ser alterado.', null=True, verbose_name='Fechado em')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reports', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('commission_rule_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commissionrule', verbose_name='Regra Aplicada')),
            ],
            options={
                'verbose_name': 'Relatório de Comissão',
                'verbose_name_plural': 'Relatórios de Comissão',
                'unique_together': {('seller', 'period_year', 'period_month')},
            },
        ),
    ]
